### ISSUE TITLE
Arrow indicator not show in new version in type Overlay

### ISSUE THREAD

**Issue by rcristobalm** [SimonVT/android-menudrawer#147]
Hi, I have changed in my application menudrawer version, I made the appropriate changes and it works ... but it shows the arrow indicator. Why? What I have to do?

thank you very much

**Comment by SimonVT** [comment]
Where would I show it? I don't think it makes sense for the overlay drawer.

**Comment by rcristobalm** [comment]
Well ... not. is that I like the idea that you indicate the menu position where we are.
perhaps with arrows on a grayish tone, as part of the right. look good, no?

**Comment by SimonVT** [comment]
No, I don't think that would look good.
The arrow made sense when the drawer was behind the content, since the arrow could look like an extension of the content. It also solved that issue that the menu view isn't able to draw its own arrow on top of the drop shadow/menu overlay. This was the reasoning behind adding an API for it. With the overlay drawer, these issues don't exist.
