### ISSUE TITLE
add a shadow on the top of the sidebar menu

### ISSUE THREAD

**Issue by pommedeterresautee** [SimonVT/android-menudrawer#15]
There is a shadow on the right side of the menu meaning the main part is on top of the slide menu.
But there is no shadow on top of the slide menu (between the actionbar and the slide menu content). Would be more realistic to add this shadow, isn't it?

I tried by myself but I don't like my solution (which is basically an onDraw() overwrite). If implemented in the lib, would be more clean and everyone would benefit from it.

**Comment by SimonVT** [comment]
The drop shadow from the action bar onto the content is added by the framework. If you only drag the content, the menu will have the same drop shadow.
When dragging the entire window it doesn't really make sense to have a drop shadow, since the action bar doesn't have one either (and the menu is top-aligned with the action bar).
