### ISSUE TITLE
Add Maven Support?

### ISSUE THREAD

**Issue by harmanjd** [SimonVT/android-menudrawer#4]
I'd like to see maven support for this library. It makes it easy to add as a dependency on my project.

**Comment by scompt** [comment]
I've added a basic pom file so that I can add the project as a dependency. To do it correctly, there probably needs to be a pom file for the whole project which contains two sub-projects, the library and samples. I've based the pom file on one of jake wharton's projects, nine old androids, I think.

You can check it out in [my maven branch](https://github.com/scompt/android-menudrawer/tree/maven).
